image: continuumio/anaconda3:2020.02
stages:
  - check-files
  - lint
  - run

check-lab-files:
  tags:
    - docker
  stage: check-files
  script:
    - test -f .gitignore
    - test -f .pylintrc
    - test -f common/describe_data.py
    - test -f common/test_env.py
    - test -f data/cc_general.csv
    - test -f results/.placeholder
    - test -f lab4.py
    - find . -name "*" -not -path "./.git/*" -not -path "./builds/*" 2>&1

lint-lab:
  tags:
    - docker
  stage: lint
  script:
    # Check formatting
    - autopep8 -d --exit-code lab4.py
    # Lint
    - pylint lab4.py

run-lab:
  tags:
    - docker
  stage: run
  script:
    - chmod +x lab4.py
    - ./lab4.py
  artifacts:
    name: lab4-results-$CI_COMMIT_SHORT_SHA
    paths:
      - results/
